const HTTP_STATUS = {
    OK: 200,  
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
    TOO_MANY_REQUESTS: 429,
}

const HTTP_CODE = { 
    OK: "OK",
    CREATED: "CREATED",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    ROUTE_NOT_FOUND:"ROUTE_NOT_FOUND",
    DATA_NOT_FOUND: "DATA_NOT_FOUND",
    CONFLICT: "CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR Server Error",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    VALIDATION:"VALIDATION",
}

module.exports = {
    HTTP_STATUS,
    HTTP_CODE
}